// Using this script to test python module importing. Specifically, katpoint and mosaic modules for delay calculation.
// Use python 3.7
// To compile it:
// gcc Delay_katpoint_mosaic.c -o Delay_katpoint_mosaic.exe -lm -I/opt/conda/include/python3.7m -L/opt/conda/lib -lpython3.7m
// And make sure that /opt/conda/lib is include in the LD_LIBRARY_PATH
// To run it:
// ./Delay_katpoint_mosaic.exe

#define PY_SSIZE_T_CLEAN
#include <Python.h>
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <time.h>
#include <unistd.h>
#include <stdint.h>
#include <endian.h>
#include <math.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <string.h>

int main()
{

	// Initialize python the python interpreter //
	Py_Initialize();

	// Import python module //
	PyObject* myModuleString = PyUnicode_DecodeFSDefault("get_delays");
	//PyObject* myModuleString = PyUnicode_DecodeFSDefaultAndSize("test_module",11);
	//PyObject* myModuleString = PyUnicode_DecodeFSDefault("func_for_C_script");
	//PyObject* myModuleString = PyUnicode_FromString("func_for_C_script");
	assert(myModuleString != NULL);
	PyObject* myModule = PyImport_Import(myModuleString);
	//PyObject* myModule = PyImport_ImportModule("func_for_C_script");
	//PyObject* myModule = PyImport_ImportModule("test_module");
	assert(myModule != NULL);
	Py_DECREF(myModuleString);
	
	// Get referrence to class //
	PyObject* myClass = PyObject_GetAttrString(myModule, "DelayPolynomial");
	assert(myClass != NULL);
	Py_DECREF(myModule);

	int arg = 0;
	int arg_flag = 1.0; // This is the argument to change the flag in the python script //
	// First argument is the size of the tuple (number of arguments).
	// Second and onward arguments are the arguments to the __init__ function of the class.
	PyObject* arglist = PyTuple_Pack(arg, PyFloat_FromDouble(arg_flag)); 
	//PyObject* arglist = PyTuple_Pack(arg, PyUnicode_DecodeFSDefault("1")); 
	assert(arglist != NULL);

	// Get class //
	PyObject* myInst = PyObject_CallObject(myClass, arglist);
	assert(myInst != NULL);

	// Get referrence to method/function //
	PyObject* myMethod  = PyObject_GetAttrString(myInst, "get_delay_polynomials"); // fetch bound method //
  	assert(myMethod != NULL);
  	Py_DECREF(myInst);

	int arg2 = 2;
	int time_arg = 1629380016;
	int dur_flag = 2;
	// No argument needed for the gen_some_vals //
	PyObject* arglist2 = PyTuple_Pack(arg2, PyFloat_FromDouble(time_arg), PyFloat_FromDouble(dur_flag));
	assert(arglist2 != NULL);

	// Get result from function //
	PyObject* myResult = PyObject_CallObject(myMethod, arglist2);
	Py_DECREF(myMethod);
	Py_DECREF(arglist2);
	assert(myResult != NULL);

	/*
	// Gets a single value from a variable in python //
	float result = (float)PyFloat_AsDouble(myResult);
	Py_DECREF(myResult);
	printf("Result from python module = %f \n", result);
	*/

	// Gets the size of the array generated by python script //
	int arr_size = PyList_Size(myResult);
	printf("Length of array = %d \n", arr_size);

	// Gets the values from the array //
	PyObject* result_tmp;
	float* result = (float*)calloc(arr_size, sizeof(float));
	for(int i = 0; i < arr_size; i++){
		result_tmp = PyList_GetItem(myResult, i);
		result[i] = (float)PyFloat_AsDouble(result_tmp);
	}

	// First beam
	printf("--------------First beam---------------\n");
	printf("idx %d in result array = %e \n", 0, result[0]);
	printf("idx %d in result array = %e \n", 1, result[1]);
	printf("idx %d in result array = %e \n", 2, result[2]);
	// Second beam
	printf("--------------Second beam--------------\n");
	printf("idx %d in result array = %e \n", 64*2, result[64*2]);
	printf("idx %d in result array = %e \n", (64*2)+2, result[(64*2)+2]);
	printf("idx %d in result array = %e \n", (64*2)+(2*2), result[(64*2)+(2*2)]);
	// Second beam next delay
	printf("--------Second beam next delay?--------\n");
	printf("idx %d in result array = %e \n", (64*2)+1, result[(64*2)+1]);
	printf("idx %d in result array = %e \n", (64*2)+2+1, result[(64*2)+2+1]);
	printf("idx %d in result array = %e \n", (64*2)+(2*2)+1, result[(64*2)+(2*2)+1]);

	Py_Finalize();

	return 0;
}
